use std::path::PathBuf;
use std::sync::Once;
use anyhow::{Result, anyhow};
use log::info;
use whisper_rs::{FullParams, SamplingStrategy, WhisperContext, WhisperContextParameters};

struct WhisperModelInfo {
    filename: &'static str,
    url: &'static str,
}

fn get_model_info(model_id: &str) -> WhisperModelInfo {
    match model_id {
        "large-v3-turbo" => WhisperModelInfo {
            filename: "ggml-large-v3-turbo.bin",
            url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin",
        },
        "large-v3" => WhisperModelInfo {
            filename: "ggml-large-v3.bin",
            url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin",
        },
        "distil-large-v3.5" => WhisperModelInfo {
            filename: "ggml-distil-large-v3.5.bin",
            url: "https://huggingface.co/distil-whisper/distil-large-v3.5-ggml/resolve/main/ggml-model.bin",
        },
        _ => WhisperModelInfo {
            filename: "ggml-large-v3.bin",
            url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin",
        },
    }
}

static SUPPRESS_WHISPER_LOGS: Once = Once::new();

// `ggml_log_level` is generated by bindgen and differs across platforms:
// - macOS: c_uint (u32)
// - Windows / Linux: c_int (i32)
#[cfg(target_os = "macos")]
type GgmlLogLevel = std::os::raw::c_uint;
#[cfg(not(target_os = "macos"))]
type GgmlLogLevel = std::os::raw::c_int;

unsafe extern "C" fn noop_log_callback(
    _level: GgmlLogLevel,
    _text: *const std::os::raw::c_char,
    _user_data: *mut std::os::raw::c_void,
) {}

fn suppress_whisper_logs() {
    SUPPRESS_WHISPER_LOGS.call_once(|| {
        unsafe {
            whisper_rs::set_log_callback(Some(noop_log_callback), std::ptr::null_mut());
        }
    });
}

lazy_static::lazy_static! {
    /// Language passed to whisper.cpp: a code like "pl", or "auto".
    static ref LANGUAGE: std::sync::Mutex<String> = std::sync::Mutex::new("auto".to_string());

    /// Language detected for the recording in progress.
    ///
    /// Detection runs on each chunk of audio, and these chunks are ~3 seconds
    /// long - far too short to decide reliably, so consecutive chunks of one
    /// meeting can come back as different languages and the transcript turns
    /// into a mix. Instead, detect once on the first chunk that carries real
    /// speech and hold that for the rest of the recording.
    static ref DETECTED_LANGUAGE: std::sync::Mutex<Option<String>> = std::sync::Mutex::new(None);
}

/// Forget the detected language. Called when a recording starts, so the next
/// meeting detects again instead of inheriting the previous one.
pub fn reset_detected_language() {
    let mut detected = DETECTED_LANGUAGE.lock().unwrap();
    *detected = None;
}

/// Set from the `transcription_language` setting at startup.
pub fn set_language(language: &str) {
    let normalised = language.trim().to_ascii_lowercase();
    let mut current = LANGUAGE.lock().unwrap();
    *current = if normalised.is_empty() {
        "auto".to_string()
    } else {
        normalised
    };
    info!("Transcription language: {}", current);
}

/// What to hand whisper.cpp for the next chunk: the configured language, the
/// one already detected for this recording, or "auto" until that happens.
fn language() -> String {
    let configured = LANGUAGE.lock().unwrap().clone();
    if configured != "auto" {
        return configured;
    }
    if let Some(detected) = DETECTED_LANGUAGE.lock().unwrap().clone() {
        return detected;
    }
    "auto".to_string()
}

/// Remember the language whisper.cpp settled on, once a chunk carried enough
/// speech for the answer to mean something.
fn remember_detected_language(state: &whisper_rs::WhisperState, text: &str) {
    if text.trim().chars().count() < 20 {
        return;
    }
    {
        let detected = DETECTED_LANGUAGE.lock().unwrap();
        if detected.is_some() {
            return;
        }
    }

    // Older whisper-rs releases spell this `full_lang_id`.
    if let Ok(id) = state.full_lang_id_from_state() {
        if let Some(code) = whisper_rs::get_lang_str(id) {
            let mut detected = DETECTED_LANGUAGE.lock().unwrap();
            *detected = Some(code.to_string());
            info!("Detected spoken language: {} - keeping it for this recording", code);
        }
    }
}

/// Threads for inference. whisper.cpp scales with physical cores and then
/// flattens out; four was hard-coded here, which left most of a modern laptop
/// unused.
fn inference_threads() -> std::os::raw::c_int {
    let available = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);
    // Leave a little room for the audio thread and the UI process.
    let threads = if available > 2 { available - 1 } else { available };
    threads.clamp(1, 8) as std::os::raw::c_int
}

pub fn model_dir() -> PathBuf {
    crate::configuration::portable::models_dir()
}

pub fn model_path(model_id: &str) -> PathBuf {
    let info = get_model_info(model_id);
    model_dir().join(info.filename)
}

pub fn is_model_downloaded(model_id: &str) -> bool {
    let path = model_path(model_id);
    path.exists() && path.metadata().map(|m| m.len() > 1_000_000).unwrap_or(false)
}

pub async fn download_model(app_handle: &tauri::AppHandle, model_id: &str) -> Result<()> {
    use tauri::Manager;

    let info = get_model_info(model_id);
    let dir = model_dir();
    std::fs::create_dir_all(&dir)?;

    let dest = model_path(model_id);
    let tmp = dest.with_extension("bin.tmp");

    info!("Downloading whisper model from {}", info.url);

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(3600))       // 1h total
        .connect_timeout(std::time::Duration::from_secs(30)) // 30s to connect
        .build()
        .map_err(|e| anyhow!("Failed to build HTTP client: {}", e))?;
    let resp = client.get(info.url).send().await
        .map_err(|e| anyhow!("Failed to start model download: {}", e))?;

    if !resp.status().is_success() {
        return Err(anyhow!("Model download failed with status {}", resp.status()));
    }

    let total_size = resp.content_length().unwrap_or(0);
    info!("Model size: {} MB", total_size / 1_048_576);

    let mut file = std::fs::File::create(&tmp)?;
    let mut downloaded: u64 = 0;
    let mut last_percent: u8 = 0;

    use futures::StreamExt;
    use std::io::Write;
    let mut stream = resp.bytes_stream();

    while let Some(chunk) = stream.next().await {
        let chunk = chunk.map_err(|e| anyhow!("Download error: {}", e))?;
        file.write_all(&chunk)?;
        downloaded += chunk.len() as u64;

        if total_size > 0 {
            let percent = ((downloaded as f64 / total_size as f64) * 100.0) as u8;
            if percent != last_percent {
                last_percent = percent;
                if let Some(w) = app_handle.get_window("main") {
                    let _ = w.emit("model-download-progress", serde_json::json!({
                        "percent": percent
                    }));
                }
            }
        }
    }

    drop(file);
    std::fs::rename(&tmp, &dest)?;
    info!("Model downloaded successfully to {:?}", dest);

    Ok(())
}

pub struct WhisperEngine {
    ctx: WhisperContext,
}

impl WhisperEngine {
    pub fn load(model_id: &str) -> Result<Self> {
        let path = model_path(model_id);
        if !path.exists() {
            return Err(anyhow!("Whisper model not found at {:?}. Download it first.", path));
        }

        suppress_whisper_logs();
        info!("Loading whisper model from {:?}", path);

        let params = WhisperContextParameters::default();
        let ctx = WhisperContext::new_with_params(
            path.to_str().ok_or_else(|| anyhow!("Invalid model path"))?,
            params,
        ).map_err(|e| anyhow!("Failed to load whisper model: {:?}", e))?;

        info!("Whisper model loaded successfully");
        Ok(Self { ctx })
    }

    pub fn transcribe(&self, samples_16k: &[f32]) -> Result<String> {
        if samples_16k.is_empty() {
            return Ok(String::new());
        }

        let mut state = self.ctx.create_state()
            .map_err(|e| anyhow!("Failed to create whisper state: {:?}", e))?;

        // Declared before `params` on purpose: FullParams borrows this string,
        // so it has to outlive it.
        let language = language();

        let mut params = FullParams::new(SamplingStrategy::Greedy { best_of: 1 });
        params.set_language(Some(&language));
        params.set_translate(false);
        params.set_single_segment(true);
        params.set_no_timestamps(true);
        params.set_print_special(false);
        params.set_print_progress(false);
        params.set_print_realtime(false);
        params.set_print_timestamps(false);
        params.set_suppress_blank(true);
        params.set_n_threads(inference_threads());

        state.full(params, samples_16k)
            .map_err(|e| anyhow!("Whisper inference failed: {:?}", e))?;

        let mut text = String::new();
        let n_segments = state.full_n_segments();

        for i in 0..n_segments {
            if let Some(segment) = state.get_segment(i) {
                if let Ok(segment_text) = segment.to_str_lossy() {
                    text.push_str(&segment_text);
                }
            }
        }

        let text = text.trim().to_string();
        if language == "auto" {
            remember_detected_language(&state, &text);
        }

        Ok(text)
    }
}
